#!/bin/bash
# shellcheck disable=SC2034

declare XX_CHANNEL_NAME='mychannel'
declare XX_CC_LANGUAGE='go'
declare XX_IMAGETAG='2.3.1'
declare XX_CC_VERSION='1.0'
declare XX_CC_NAME='simplerecord'
declare XX_DB_TYPE='golevel'
declare XX_CC_PARAMETERS='"AddRecord"'
declare XX_CC_INIT_REQUIRED='false'
declare XX_TRANSIENT_DATA='{"Point":"'$(echo '{"temperature": 0.1}' | base64 | tr -d \\n)'"}'
declare XX_EXPOSE_ENDPOINTS='false'
declare XX_BLOCK_NUMBER='newest'
declare XX_CC_PRIVATE='true'
declare XX_CC_POLICY='Cg=='
declare XX_CURRENT_ORG=org0.example.com
declare XX_RUN_OUTPUT=minifab
