{
 "title": "Fabric 2.1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fabric Version",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "fabric_version" }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(ledger_transaction_count[1m]))"
    }
   ]
  },
  {
   "title": "Failures per second during  last minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(chaincode_execute_timeouts[1m]))"
    },
    {
     "expr": "sum(rate(chaincode_launch_failures[1h]))"
    },
    {
     "expr": "sum(rate(chaincode_launch_timeouts[1h]))"
    },
    {
     "expr": "sum(rate(endorser_chaincode_instantiation_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_duplicate_transaction_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_endorsement_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_proposal_acl_failures[1h]))"
    },
    {
     "expr": "sum(rate(endorser_proposal_validation_failures[1h]))"
    }
   ]
  },
  {
   "title": "Block procesing time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "ledger_block_processing_time_bucket \n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Chaincode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Chaincode Shim Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received[5m])"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed[5m])"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total[5m])"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed[5m])"
    }
   ]
  },
  {
   "title": "Chaincode Launch Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chaincode_launch_duration_count"
    },
    { "expr": "chaincode_launch_duration_sum" }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Ledger Height Per Channel",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "ledger_blockchain_height" }
   ]
  },
  {
   "title": "Ledger Block Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ledger_block_processing_time_bucket) by (le)"
    }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(ledger_transaction_count[5m])"
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ledger_statedb_commit_time_bucket) by (le)"
    }
   ]
  },
  {
   "title": "Amount of business transactions per channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\"}) by (channel)"
    }
   ]
  },
  { "title": "Orderers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Orderer Broadcasts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(broadcast_processed_count{type=\"ENDORSER_TRANSACTION\"}) by(instance)"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Successful",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(endorser_successful_proposals[5m])"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Requests",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(endorser_proposals_received[5m])"
    }
   ]
  },
  { "title": "Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } }
 ]
}