---
- name: Set up sdk release
  set_fact:
    sdk_release: "{{ IMAGETAG }}"
    caliper_release: "0.4.2"

- name: Make sure that caliper holding directory exists
  file:
    path: "{{ pjroot }}/vars/caliper/workspace/config"
    state: "{{ item }}"
    mode: 0777
  with_items:
    - "absent"
    - "directory"

- name: Create Caliper Profiles
  template:
    src: "{{ pjroot }}/playbooks/ops/caliperrun_panta/templates/{{ item }}.j2"
    dest: "{{ pjroot }}/vars/caliper/workspace/{{ item }}"
  with_items:
    - 'caliper.yaml'
    - 'benchmark-config.yaml'
    - 'network-config.yaml'

- name: Create Caliper Connection Profile
  template:

- name: Change var file permission
  command: >-
    chown -R 1000:1000 {{ pjroot }}/vars/keyfiles
    chown -R 1000:1000 {{ pjroot }}/vars/caliper

- name: Check bond caliper image
  command: >-
    docker image ls -q hyperledger/caliper_fabric:{{ sdk_release }}
  register: imagestatus

- name: Produce image if caliper bond image does not exist
  when: imagestatus.stdout_lines|length == 0
  block:
    - name: Run a container to bind fabric sdk
      command: >-
        docker run --network {{ NETNAME }} --name calipertester --hostname calipertester
        --entrypoint /run/caliperbind.sh
        -v {{ hostroot }}/vars/run:/run
        -e TZ="Asia/Shanghai"
        hyperledger/caliper:{{ caliper_release }}

    - name: Save the container as an image
      command: >-
        docker commit calipertester hyperledger/caliper_fabric:{{ sdk_release }}

    - name: Remove the docker container
      command: >-
        docker rm -f calipertester

#- name: Docker Copy Caliper files
#  copy:
#    src: "{{ pjroot }}/playbooks/ops/caliper/fabcar"
#    dest: "{{ pjroot }}/vars/caliper/workspace"

- name: Launch caliper test
  command: >-
    docker run --network {{ NETNAME }} --name calipertester --hostname calipertester --rm
    -e TZ=Asia/Shanghai
    -v /var/run/docker.sock:/var/run/docker.sock
    -v {{ hostroot }}/vars/caliper/workspace:/hyperledger/caliper/workspace
    hyperledger/caliper_fabric:{{ sdk_release }} launch manager
  register: runresults

- name: Caliper test run
  when: runresults.rc != 0
  debug:
    msg: "{{ runresults.stderr_lines }}"
  tags: [print_action]

- name: Caliper test run
  when: runresults.rc == 0
  debug:
    msg: "View results in vars/report.html"
  tags: [print_action]
