---
- name: Set up app sdk release
  set_fact:
    APP_LANGUAGE: "node"

- name: Create apprun script
  template:
    src: "{{ pjroot }}/playbooks/ops/apprun/templates/apprun_{{
          APP_LANGUAGE }}.j2"
    dest: "{{ pjroot }}/vars/run/apprun.sh"
    mode: +x

- name: Run the chaincode application
  command: >-
    docker run --network {{ NETNAME }} --name apprun --hostname apprun --rm
    -v /var/run/docker.sock:/var/run/docker.sock
    -v {{ hostroot }}/vars/profiles:/vars/profiles
    -v {{ hostroot }}/vars/app/{{ APP_LANGUAGE }}:/go/src/github.com/app
    -v {{ hostroot }}/vars/run/apprun.sh:/vars/run/apprun.sh
    -e TZ="Asia/Shanghai"
    --entrypoint /vars/run/apprun.sh
    {{ LANGUAGEENVS[APP_LANGUAGE] }}
  register: runstates

- name: App run
  when: runstates.rc != 0
  debug:
    msg: "{{ runstates.stderr_lines }}"
  tags: [print_action]

- name: App run
  when: runstates.rc == 0
  debug:
    msg: "Application in {{ APP_LANGUAGE }} completed successfully"
  tags: [print_action]
