OPNAMES:
  ccinstall: "cc install"
  ccapprove: "cc approve"
  cccommit: "cc commit"
  ccinstantiate: "cc initialize"
  ccinvoke: "cc invoke"
  ccquery: "cc query"
  channelcreate: "channel create"
  channeljoin: "channel join"
  blockquery: "block query"
  channelquery: "channel query"
  profilegen: "profiles generation"
  channelsign: "channel signoff"
  channelupdate: "channel update"
  anchorupdate: "anchor update"
  dashup: "dashboard up"
  dashdown: "dashboard down"
  nodeimport: "node import"
  discover: "discover"
  imageget: "download images"
  certgen: "generate certificates"
  certrem: "remove certificates"
  netup: "start network"
  netdown: "shutdown network"
  filerem: "cleanup working directory"
  netstats: "network status"
  optionverify: "verify options"
  explorerup: "start explorer"
  explorerdown: "shutdown explorer"
  portainerup: "start portainer"
  portainerdown: "stop portainer"
  apprun: "run chaincode application"
  caliper: "run caliper test"
  update: "update Minifabric"
  configmerge: "merge configuration"
  monitor: "prometheus"
PRECONDITIONS:
  ccinstall: ['PEER']
  ccapprove: ['PEER', 'ORDERER']
  cccommit: ['PEER', 'ORDERER']
  ccinstantiate: ['PEER', 'ORDERER']
  ccinvoke: ['PEER', 'ORDERER']
  ccquery: ['PEER']
  channelcreate: ['PEER', 'ORDERER']
  channeljoin: ['PEER', 'ORDERER']
  blockquery: ['PEER']
  channelquery: ['PEER', 'ORDERER']
  profilegen: []
  channelsign: ['PEER', 'ORDERER']
  channelupdate: ['PEER', 'ORDERER']
  anchorupdate: ['PEER', 'ORDERER']
  dashup: []
  dashdown: []
  nodeimport: ['PEER', 'ORDERER']
  discover: ['PEER', 'ORDERER']
  imageget: []
  certgen: []
  certrem: []
  netup: []
  netdown: []
  filerem: []
  netstats: []
  optionverify: []
  explorerup: []
  explorerdown: []
  portainerup: []
  portainerdown: []
  apprun: ['PEER', 'ORDERER']
  caliperrun: ['PEER', 'ORDERER']
  update: []
  configmerge: []
  caliper: ['PEER', 'ORDERER']
  monitor: []
LANGUAGEENVS:
  java: 'gradle:jdk8'
  go: 'golang:1.16'
  node: 'node:12.20.0-alpine3.12'
CALIPER_FABRIC_SDK_RELEASE: 2.2
CALIPER_RELEASE: 0.4.2
TIMEZONE: /etc/localtime:/etc/localtime